pipeline {
    
    agent {
        node {
            label 'AGENT-1'   // it will connect to agent1
        }
    }
   
    options {
        timeout(time: 1, unit: 'HOURS')  // it will timeout in 1 hour
        disableConcurrentBuilds()    // It wont allow multiple builds at a time. allows one by one only
    }

    //build

    stages {
        
        stage('Init') {
            steps {
                sh """
                cd 01-vpc
                terraform init --reconfigure
                """
            }
        }
        
        stage('Plan') {
            steps {
                sh """
                cd 01-vpc
                terraform plan
                """
            }
        }
        
        stage('Deploy') {
            steps {
                input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
                sh """
                cd 01-vpc
                terraform apply -auto-approve
                """
            }
        }

        stage('check Params') {
            steps {
                sh """
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
                """
            }
        }
    }
 
    // Post Build
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    
        failure { 
            echo 'This runs when pipeline fails, used generally to send some alerts'
        }

        success { 
            echo 'I will say Hello when pipeline succeeds'
        }
    }
}